
networks:
  app-network: # Custom network for all services
    driver: bridge

services:
  nginx:
    depends_on:
      backend:
        required: true
        condition: service_healthy
        restart: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nginx_server
    ports:
      - "80:80" # Expose NGINX on port 80
#    image: nginx
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - ./frontend/dist:/usr/share/nginx/html
    networks:
      - app-network

  backend:

    depends_on:
      postgres:
        required: true
        condition: service_started
        restart: true
    container_name:
      my-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@our-postgres/mydb
      - JWT_SECRET="lksf)2*@fn2f"
    ports:
      - "3000:3000"
    networks:
      - app-network

  postgres:
    container_name: our-postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - app-network